export default function ReviewTags({ garment, onBack, onSave }) {
  if (!garment) return null

  return (
    <div className="max-w-md mx-auto p-6">
      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <button onClick={onBack} className="text-gray-500 hover:text-gray-800">
          ← Back
        </button>
        <h1 className="text-2xl font-bold text-gray-800">Review Tags</h1>
      </div>

      <p className="text-gray-500 mb-4">Confirm or edit garment details</p>

      {/* Cutout Preview */}
      <div className="bg-white rounded-xl shadow-sm p-4 mb-4 flex items-center justify-center h-48">
        <img
          src={`http://localhost:8000/${garment.cutout}`}
          alt="Garment cutout"
          className="h-full object-contain"
          onError={(e) => { e.target.style.display = 'none' }}
        />
      </div>

      {/* Dominant Colors */}
      <div className="bg-white rounded-xl shadow-sm p-4 mb-4">
        <p className="text-sm font-medium text-gray-700 mb-2">Dominant Colors</p>
        <div className="flex gap-3">
          {garment.dominant_colors?.map((color, i) => (
            <div key={i} className="flex flex-col items-center gap-1">
              <div
                className="w-10 h-10 rounded-full border border-gray-200"
                style={{ backgroundColor: color.hex }}
              />
              <span className="text-xs text-gray-500">{color.hex}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Tags */}
      <div className="bg-white rounded-xl shadow-sm p-4 mb-6">
        <p className="text-sm font-medium text-gray-700 mb-3">
          Tags 
          <span className="text-xs text-gray-400 ml-2">
            (will be auto-generated by AI — editable here)
          </span>
        </p>

        {/* Formality */}
        <div className="mb-3">
          <p className="text-xs text-gray-500 mb-1">Formality</p>
          <div className="flex gap-2">
            {["Casual", "Smart Casual", "Formal"].map(tag => (
              <span key={tag} className="px-3 py-1 bg-gray-100 rounded-full text-xs text-gray-700">
                {tag}
              </span>
            ))}
          </div>
        </div>

        {/* Season */}
        <div className="mb-3">
          <p className="text-xs text-gray-500 mb-1">Season</p>
          <div className="flex gap-2">
            {["Spring", "Summer", "Autumn", "Winter"].map(tag => (
              <span key={tag} className="px-3 py-1 bg-gray-100 rounded-full text-xs text-gray-700">
                {tag}
              </span>
            ))}
          </div>
        </div>

        {/* Pattern */}
        <div className="mb-3">
          <p className="text-xs text-gray-500 mb-1">Pattern</p>
          <div className="flex gap-2 flex-wrap">
            {["Solid", "Striped", "Checked", "Graphic", "Floral"].map(tag => (
              <span key={tag} className="px-3 py-1 bg-gray-100 rounded-full text-xs text-gray-700">
                {tag}
              </span>
            ))}
          </div>
        </div>

        {/* Occasion */}
        <div>
          <p className="text-xs text-gray-500 mb-1">Occasion</p>
          <div className="flex gap-2 flex-wrap">
            {["Casual", "Office", "Party", "Date", "Farewell"].map(tag => (
              <span key={tag} className="px-3 py-1 bg-gray-100 rounded-full text-xs text-gray-700">
                {tag}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Save Button */}
      <button
        onClick={onSave}
        className="w-full bg-black text-white py-3 rounded-xl font-medium hover:bg-gray-800 transition"
      >
        Save to Wardrobe
      </button>
    </div>
  )
}